#!/bin/sh

# History won't save duplicates.
setopt HIST_IGNORE_ALL_DUPS
# History won't show duplicates on search.
setopt HIST_FIND_NO_DUPS

# colors
autoload -Uz colors && colors

# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments

############## completions ##############
autoload -Uz compinit && compinit
# compinit #https://apple.stackexchange.com/questions/296477/my-command-line-says-complete13-command-not-found-compdef

zstyle ':completion:*' menu select # menu like movement
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' # tab completion case insensitive
zmodload zsh/complist
_comp_options+=(globdots)		# Include hidden files in tab completion
