#!/bin/sh

alias rc='vim -c "normal Gzz" $ZDOTDIR/.zshrc'
alias sc='source $ZDOTDIR/.zshrc'
alias c='clear -x'
alias history="history -t '%F'"
#alias history="history -t '%F %T'"
alias cp="cp -v"
alias mv="mv -v"
alias path="print -l $path" #print path in a human readable way
