#!/bin/sh

export EDITOR="nvim"
export VISUAL="nvim"

# nvm (node)
export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix nvm)/nvm.sh" ] && source "$(brew --prefix nvm)/nvm.sh" # This loads nvm

## Commented and kept here for reference. Move it to the specific section
# rust
# . "$HOME/.cargo/env"

# maven path
# export MAVEN_HOME=/usr/local/Cellar/maven/3.6.3_1
# export PATH=$MAVEN_HOME/bin:$PATH

# java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

# go path
export PATH="$HOME/go/bin:$PATH"
